;PSOS Version 1.0
;Copyright (C) 2016 Ben Stockett.

;This file is part of PSOS (Pretty Simple/Stupid Operating System).

;PSOS is free software: you can redistribute it and/or modify
;it under the terms of the GNU General Public License as published by
;the Free Software Foundation, either version 3 of the License, or
;(at your option) any later version.

;PSOS is distributed in the hope that it will be useful,
;but WITHOUT ANY WARRANTY; without even the implied warranty of
;MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;GNU General Public License for more details.

;You should have received a copy of the GNU General Public License
;along with PSOS.  If not, see <http://www.gnu.org/licenses/>.

%define ATTR_BLINK 10000000b
%define ATTR_BOLD 10000000b

%define BG_BLUE 00010000b
%define BG_CYAN 00110000b
%define BG_GREEN 00100000b
%define BG_MAGENTA 01010000b
%define BG_RED 01000000b
%define BG_WHITE 01110000b
%define BG_YELLOW 01100000b

%define FG_BLUE 00000001b
%define FG_CYAN 00000011b
%define FG_GREEN 00000010b
%define FG_MAGENTA 00001010b
%define FG_RED 00000100b
%define FG_WHITE 00000111b
%define FG_YELLOW 00000110b
